[versions]
errorprone = "2.36.0"
guava = "33.4.0-jre"
immutables = "2.10.1"
junit = "5.11.4"
log4j = "2.24.3"
more-commons = "5.1.0"
slf4j = "2.0.16"

errorprone-plugin = "5.0.0"
maven-publish-plugin = "0.36.0"
versions-plugin = "0.53.0"

[libraries]
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
immutables-value = { module = "org.immutables:value", version.ref = "immutables" }
immutables-annotations = { module = "org.immutables:value-annotations", version.ref = "immutables" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
log4j-bom = { module = "org.apache.logging.log4j:log4j-bom", version.ref = "log4j" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl" }
more-commons = { module = "com.arakelian:more-commons", version.ref = "more-commons" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
jcl-over-slf4j = { module = "org.slf4j:jcl-over-slf4j", version.ref = "slf4j" }
jul-to-slf4j = { module = "org.slf4j:jul-to-slf4j", version.ref = "slf4j" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish-plugin" }
